name: Semantic Release

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check_pr_title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Pull Request title
        uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
